/*
Dam Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DamListAssetsByCodesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DamListAssetsByCodesResponse{}

// DamListAssetsByCodesResponse struct for DamListAssetsByCodesResponse
type DamListAssetsByCodesResponse struct {
	Assets []DamAsset `json:"assets,omitempty"`
}

// NewDamListAssetsByCodesResponse instantiates a new DamListAssetsByCodesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDamListAssetsByCodesResponse() *DamListAssetsByCodesResponse {
	this := DamListAssetsByCodesResponse{}
	return &this
}

// NewDamListAssetsByCodesResponseWithDefaults instantiates a new DamListAssetsByCodesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDamListAssetsByCodesResponseWithDefaults() *DamListAssetsByCodesResponse {
	this := DamListAssetsByCodesResponse{}
	return &this
}

// GetAssets returns the Assets field value if set, zero value otherwise.
func (o *DamListAssetsByCodesResponse) GetAssets() []DamAsset {
	if o == nil || IsNil(o.Assets) {
		var ret []DamAsset
		return ret
	}
	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DamListAssetsByCodesResponse) GetAssetsOk() ([]DamAsset, bool) {
	if o == nil || IsNil(o.Assets) {
		return nil, false
	}
	return o.Assets, true
}

// HasAssets returns a boolean if a field has been set.
func (o *DamListAssetsByCodesResponse) HasAssets() bool {
	if o != nil && !IsNil(o.Assets) {
		return true
	}

	return false
}

// SetAssets gets a reference to the given []DamAsset and assigns it to the Assets field.
func (o *DamListAssetsByCodesResponse) SetAssets(v []DamAsset) {
	o.Assets = v
}

func (o DamListAssetsByCodesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DamListAssetsByCodesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Assets) {
		toSerialize["assets"] = o.Assets
	}
	return toSerialize, nil
}

type NullableDamListAssetsByCodesResponse struct {
	value *DamListAssetsByCodesResponse
	isSet bool
}

func (v NullableDamListAssetsByCodesResponse) Get() *DamListAssetsByCodesResponse {
	return v.value
}

func (v *NullableDamListAssetsByCodesResponse) Set(val *DamListAssetsByCodesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDamListAssetsByCodesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDamListAssetsByCodesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDamListAssetsByCodesResponse(val *DamListAssetsByCodesResponse) *NullableDamListAssetsByCodesResponse {
	return &NullableDamListAssetsByCodesResponse{value: val, isSet: true}
}

func (v NullableDamListAssetsByCodesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDamListAssetsByCodesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


