/*
Dam Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DamUpdateAssetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DamUpdateAssetRequest{}

// DamUpdateAssetRequest struct for DamUpdateAssetRequest
type DamUpdateAssetRequest struct {
	TenantId string `json:"tenantId"`
	Id string `json:"id"`
	Payload *UpdateAssetRequestPayload `json:"payload,omitempty"`
	PayloadMask *string `json:"payloadMask,omitempty"`
}

type _DamUpdateAssetRequest DamUpdateAssetRequest

// NewDamUpdateAssetRequest instantiates a new DamUpdateAssetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDamUpdateAssetRequest(tenantId string, id string) *DamUpdateAssetRequest {
	this := DamUpdateAssetRequest{}
	this.TenantId = tenantId
	this.Id = id
	return &this
}

// NewDamUpdateAssetRequestWithDefaults instantiates a new DamUpdateAssetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDamUpdateAssetRequestWithDefaults() *DamUpdateAssetRequest {
	this := DamUpdateAssetRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *DamUpdateAssetRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *DamUpdateAssetRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *DamUpdateAssetRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetId returns the Id field value
func (o *DamUpdateAssetRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DamUpdateAssetRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DamUpdateAssetRequest) SetId(v string) {
	o.Id = v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *DamUpdateAssetRequest) GetPayload() UpdateAssetRequestPayload {
	if o == nil || IsNil(o.Payload) {
		var ret UpdateAssetRequestPayload
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DamUpdateAssetRequest) GetPayloadOk() (*UpdateAssetRequestPayload, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *DamUpdateAssetRequest) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given UpdateAssetRequestPayload and assigns it to the Payload field.
func (o *DamUpdateAssetRequest) SetPayload(v UpdateAssetRequestPayload) {
	o.Payload = &v
}

// GetPayloadMask returns the PayloadMask field value if set, zero value otherwise.
func (o *DamUpdateAssetRequest) GetPayloadMask() string {
	if o == nil || IsNil(o.PayloadMask) {
		var ret string
		return ret
	}
	return *o.PayloadMask
}

// GetPayloadMaskOk returns a tuple with the PayloadMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DamUpdateAssetRequest) GetPayloadMaskOk() (*string, bool) {
	if o == nil || IsNil(o.PayloadMask) {
		return nil, false
	}
	return o.PayloadMask, true
}

// HasPayloadMask returns a boolean if a field has been set.
func (o *DamUpdateAssetRequest) HasPayloadMask() bool {
	if o != nil && !IsNil(o.PayloadMask) {
		return true
	}

	return false
}

// SetPayloadMask gets a reference to the given string and assigns it to the PayloadMask field.
func (o *DamUpdateAssetRequest) SetPayloadMask(v string) {
	o.PayloadMask = &v
}

func (o DamUpdateAssetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DamUpdateAssetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["id"] = o.Id
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !IsNil(o.PayloadMask) {
		toSerialize["payloadMask"] = o.PayloadMask
	}
	return toSerialize, nil
}

func (o *DamUpdateAssetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDamUpdateAssetRequest := _DamUpdateAssetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDamUpdateAssetRequest)

	if err != nil {
		return err
	}

	*o = DamUpdateAssetRequest(varDamUpdateAssetRequest)

	return err
}

type NullableDamUpdateAssetRequest struct {
	value *DamUpdateAssetRequest
	isSet bool
}

func (v NullableDamUpdateAssetRequest) Get() *DamUpdateAssetRequest {
	return v.value
}

func (v *NullableDamUpdateAssetRequest) Set(val *DamUpdateAssetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDamUpdateAssetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDamUpdateAssetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDamUpdateAssetRequest(val *DamUpdateAssetRequest) *NullableDamUpdateAssetRequest {
	return &NullableDamUpdateAssetRequest{value: val, isSet: true}
}

func (v NullableDamUpdateAssetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDamUpdateAssetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


