/*
Dam Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dam

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DamListAssetsByCodesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DamListAssetsByCodesRequest{}

// DamListAssetsByCodesRequest struct for DamListAssetsByCodesRequest
type DamListAssetsByCodesRequest struct {
	TenantId string `json:"tenantId"`
	Codes []string `json:"codes"`
}

type _DamListAssetsByCodesRequest DamListAssetsByCodesRequest

// NewDamListAssetsByCodesRequest instantiates a new DamListAssetsByCodesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDamListAssetsByCodesRequest(tenantId string, codes []string) *DamListAssetsByCodesRequest {
	this := DamListAssetsByCodesRequest{}
	this.TenantId = tenantId
	this.Codes = codes
	return &this
}

// NewDamListAssetsByCodesRequestWithDefaults instantiates a new DamListAssetsByCodesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDamListAssetsByCodesRequestWithDefaults() *DamListAssetsByCodesRequest {
	this := DamListAssetsByCodesRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *DamListAssetsByCodesRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *DamListAssetsByCodesRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *DamListAssetsByCodesRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetCodes returns the Codes field value
func (o *DamListAssetsByCodesRequest) GetCodes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Codes
}

// GetCodesOk returns a tuple with the Codes field value
// and a boolean to check if the value has been set.
func (o *DamListAssetsByCodesRequest) GetCodesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Codes, true
}

// SetCodes sets field value
func (o *DamListAssetsByCodesRequest) SetCodes(v []string) {
	o.Codes = v
}

func (o DamListAssetsByCodesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DamListAssetsByCodesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["codes"] = o.Codes
	return toSerialize, nil
}

func (o *DamListAssetsByCodesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"codes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDamListAssetsByCodesRequest := _DamListAssetsByCodesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDamListAssetsByCodesRequest)

	if err != nil {
		return err
	}

	*o = DamListAssetsByCodesRequest(varDamListAssetsByCodesRequest)

	return err
}

type NullableDamListAssetsByCodesRequest struct {
	value *DamListAssetsByCodesRequest
	isSet bool
}

func (v NullableDamListAssetsByCodesRequest) Get() *DamListAssetsByCodesRequest {
	return v.value
}

func (v *NullableDamListAssetsByCodesRequest) Set(val *DamListAssetsByCodesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDamListAssetsByCodesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDamListAssetsByCodesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDamListAssetsByCodesRequest(val *DamListAssetsByCodesRequest) *NullableDamListAssetsByCodesRequest {
	return &NullableDamListAssetsByCodesRequest{value: val, isSet: true}
}

func (v NullableDamListAssetsByCodesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDamListAssetsByCodesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


