/*
Dam Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dam

import (
	"encoding/json"
)

// checks if the DamListAssetsByIdsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DamListAssetsByIdsResponse{}

// DamListAssetsByIdsResponse struct for DamListAssetsByIdsResponse
type DamListAssetsByIdsResponse struct {
	Assets []DamAsset `json:"assets,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DamListAssetsByIdsResponse DamListAssetsByIdsResponse

// NewDamListAssetsByIdsResponse instantiates a new DamListAssetsByIdsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDamListAssetsByIdsResponse() *DamListAssetsByIdsResponse {
	this := DamListAssetsByIdsResponse{}
	return &this
}

// NewDamListAssetsByIdsResponseWithDefaults instantiates a new DamListAssetsByIdsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDamListAssetsByIdsResponseWithDefaults() *DamListAssetsByIdsResponse {
	this := DamListAssetsByIdsResponse{}
	return &this
}

// GetAssets returns the Assets field value if set, zero value otherwise.
func (o *DamListAssetsByIdsResponse) GetAssets() []DamAsset {
	if o == nil || IsNil(o.Assets) {
		var ret []DamAsset
		return ret
	}
	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DamListAssetsByIdsResponse) GetAssetsOk() ([]DamAsset, bool) {
	if o == nil || IsNil(o.Assets) {
		return nil, false
	}
	return o.Assets, true
}

// &#39;Has&#39;Assets returns a boolean if a field has been set.
func (o *DamListAssetsByIdsResponse) &#39;Has&#39;Assets() bool {
	if o != nil && !IsNil(o.Assets) {
		return true
	}

	return false
}

// SetAssets gets a reference to the given []DamAsset and assigns it to the Assets field.
func (o *DamListAssetsByIdsResponse) SetAssets(v []DamAsset) {
	o.Assets = v
}

func (o DamListAssetsByIdsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DamListAssetsByIdsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Assets) {
		toSerialize["assets"] = o.Assets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DamListAssetsByIdsResponse) UnmarshalJSON(data []byte) (err error) {
	varDamListAssetsByIdsResponse := _DamListAssetsByIdsResponse{}

	err = json.Unmarshal(data, &varDamListAssetsByIdsResponse)

	if err != nil {
		return err
	}

	*o = DamListAssetsByIdsResponse(varDamListAssetsByIdsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "assets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *DamListAssetsByIdsResponse) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *DamListAssetsByIdsResponse) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableDamListAssetsByIdsResponse struct {
	value *DamListAssetsByIdsResponse
	isSet bool
}

func (v NullableDamListAssetsByIdsResponse) Get() *DamListAssetsByIdsResponse {
	return v.value
}

func (v *NullableDamListAssetsByIdsResponse) Set(val *DamListAssetsByIdsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDamListAssetsByIdsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDamListAssetsByIdsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDamListAssetsByIdsResponse(val *DamListAssetsByIdsResponse) *NullableDamListAssetsByIdsResponse {
	return &NullableDamListAssetsByIdsResponse{value: val, isSet: true}
}

func (v NullableDamListAssetsByIdsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDamListAssetsByIdsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


